version: '3'

services:
  php73:
    image: wordpress:php7.3-fpm
    restart: always
    networks:
      - internal
    volumes:
      - $PWD/html:/var/www/html:rw
  nginx:
    image: nginx 
    restart: always
    networks:
      - internal
      - web
    volumes:
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/html:/var/www/html:rw
    labels:
      - "traefik.enable=true"
      - "traefik.backend=paulotech"
      - "traefik.frontend.rule=Host:seusite.com.br"
      - "traefik.port=80"
      - "traefik.docker.network=web"

  mariadb:
    image: mariadb
    restart: always
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - $PWD/datadir:/var/lib/mysql:rw

networks:
  web:
    external: true
  internal:
    external: false
